version: "3.7"

services:
  app:
    container_name: todo-api-container
    build: .
    command: npm run start:dev
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOSTNAME: mysql

  mysql: # Example Service
    container_name: todo-api-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${USUARIO_BANCO_DADOS}
      - MYSQL_PASSWORD=${SENHA_BANCO_DADOS}
      - MYSQL_DATABASE=todo
    ports:
    - "3308:3306"
    volumes:
    - todo_mysql_data:/var/lib/mysql

volumes:
  todo_mysql_data:

networks:
  default:
    external:
      name: local